name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull kapil782/gemini-ai:latest

    - name: Delete Old Docker container
      run: sudo docker rm -f gemini-ai || true

    - name: Run Docker container
      run: sudo docker run -d -p 5000:5000 --name gemini-ai kapil782/gemini-ai:latest